"""Add marketplace phase 2 models

Revision ID: 84e290de81a2
Revises: f6a6f7e3d846
Create Date: 2026-10-06 11:15:31.505145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e290de81a2'
down_revision: Union[str, Sequence[str], None] = 'f6a6f7e3d846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
