"""Add user profile fields

Revision ID: f6a6f7e3d846
Revises: 54c4ca0be34d
Create Date: 2026-10-06 11:06:42.612477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a6f7e3d846'
down_revision: Union[str, Sequence[str], None] = '54c4ca0be34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('users', sa.Column('expertise', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('completed_orders', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'completed_orders')
    op.drop_column('users', 'rating')
    op.drop_column('users', 'expertise')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
